# Generated by Django 5.2.4 on 2025-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garageservice',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='garageservice',
            name='opening_hours',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
